[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
line-length = 120
src = ["src", "test"]
target-version = "py38"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203", # one-blank-line-before-class
    "D212", # summary line in docstrings will start with the second raw
    "D413", # not applicable for numpy docstrings
    "EM101", # raw-string-in-exception
    "EM102", # we want to use f string in exception messages
    "TRY003", # we want to write long exception messages
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 72

[tool.mypy]
python_version = "3.8"
warn_return_any = true
